version: "3"
services:
  container1:
    image: nginx:alpine
    # container_name: container1
    ports:
      - 9091:80
    # volumes:
    #   - esdata1:/usr/share/elasticsearch/data
    networks:
      - backend
  container2:
    build:
      dockerfile: Dockerfile
      build: ../go-module
    ports:
      - 9090:8080
    networks:
    - backend
networks:
  backend: